"use strict";
/**
 * PactPay - Shared Type Definitions
 *
 * These types are shared between Cloud Functions and frontend
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_CODES = void 0;
// Error Codes
exports.ERROR_CODES = {
    ACCOUNT_NOT_CONNECTED: 'ACCOUNT_NOT_CONNECTED',
    RECIPIENT_NOT_CONNECTED: 'RECIPIENT_NOT_CONNECTED',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
    PROTECTED_FUNDS_NOT_SPENDABLE: 'PROTECTED_FUNDS_NOT_SPENDABLE',
    INVALID_PAYMENT_STATE: 'INVALID_PAYMENT_STATE',
    PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
    PAYMENT_ALREADY_RECOVERED: 'PAYMENT_ALREADY_RECOVERED',
    PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
    VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
    VERIFICATION_FAILED: 'VERIFICATION_FAILED',
    UNAUTHORIZED_OPERATION: 'UNAUTHORIZED_OPERATION',
    IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
    DEMO_FUNDS_ALREADY_ISSUED: 'DEMO_FUNDS_ALREADY_ISSUED',
    TREASURY_ERROR: 'TREASURY_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
    INVALID_BANK: 'INVALID_BANK',
};
//# sourceMappingURL=index.js.map